# Generated by Django 6.0.4 on 2026-04-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product')]},
        ),
    ]
