# Generated by Django 6.0.4 on 2026-04-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product'), ('can_view_product', 'Can view product'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user'), ('can_delete_user', 'Can delete user'), ('view_stock', 'Can view inventory'), ('edit_stock', 'Can edit stock'), ('delete_stock', 'Can delete stock'), ('view_sales', 'Can view sales'), ('create_sale', 'Can create sale')]},
        ),
    ]
