# Generated by Django 6.0.4 on 2026-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_sale_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
