# Generated by Django 5.2.12 on 2026-05-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_review_unique_together_review_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
