# Generated by Django 5.2.12 on 2026-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic attributes e.g. {'RAM': '16GB'}"),
        ),
    ]
