# Generated by Django 5.2.12 on 2026-05-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_order_orderstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing savings', max_digits=10, null=True),
        ),
    ]
